name: test

on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: retrieve repo
      uses: actions/checkout@v1
    - name: run tests
      shell: powershell
      run: Invoke-Pester
